apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: 1rajboricha/backstage-k8s:v1
          ports:
            - containerPort: 7007
          env:
            - name: APP_CONFIG_app_baseUrl
              value: "https://backstage.test.com"
            - name: APP_CONFIG_backend_baseUrl
              value: "https://backstage.test.com"
            - name: POSTGRES_USER
              value: "backstage"
            - name: POSTGRES_PASSWORD
              value: "backstage"
            - name: POSTGRES_HOST
              value: "psql-postgresql"
            - name: POSTGRES_DB_PASSWORD
              value: "backstage"
            - name: GITHUB_TOKEN
              value: "$GITHUB_TOKEN"
            - name: AUTH_GITHUB_CLIENT_ID
              value: "Ov23liENyyUZntYfbjsh"
            - name: AUTH_GITHUB_CLIENT_SECRET
              value: "01cc8010c6cd7ab1a091062137a8b1e0aaa82b6a"
---
apiVersion: v1
kind: Service
metadata:
  name: backstage-service
spec:
  selector:
    app: backstage
  ports:
  - port: 7007
    protocol: TCP
    targetPort: 7007
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage
  labels:
    app.kubernetes.io/name: backstage
spec:
  rules:
  - host: "backstage.test.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: backstage-service
            port: 
              number: 7007
