# Backstage override configuration for your local development environment
app:
  listen:
    host: 0.0.0.0
    port: 7007
  baseUrl: ${APP_CONFIG_app_baseUrl}
backend:
  baseUrl: ${APP_CONFIG_backend_baseUrl}
  listen:
    port: 7007
    host: 0.0.0.0

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: 5432
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        ## uncomment if using GitHub Enterprise
        # enterpriseInstanceUrl: ${AUTH_GITHUB_ENTERPRISE_INSTANCE_URL}
        signIn:
          resolvers:
            # Matches the GitHub username with the Backstage user entity name.
            # See https://backstage.io/docs/auth/github/provider#resolvers for more resolvers.
            - resolver: usernameMatchingUserEntityName


catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: /app/entities/users.yaml
      rules:
        - allow: [User]

    - type: file
      target: /app/entities/groups.yaml
      rules:
        - allow: [Group]

    - type: url
      target: https://github.com/vanrajboricha/backstage-software-template/blob/main/python-app/template.yaml
      rules:
        - allow: [Template]

    - type: url
      target: https://github.com/vanrajboricha/backstage-software-template/blob/main/nodejs/template.yaml
      rules:
        - allow: [Template]

proxy:
  endpoints:                          # ← add this level
    '/prometheus/api':
      target: ${PROMETHEUS_URL}
      changeOrigin: true
      secure: false
      pathRewrite:
        '^/api/proxy/prometheus/api/?': '/'


argocd:
  baseUrl: https://argocd-server.argocd.svc.cluster.local
  username: admin
  password: ${ARGOCD_PASSWORD}

prometheus:
  proxyPath: /prometheus/api

grafana:
  token: ${GRAFANA_TOKEN}
  hosts:
    - domain: ${GRAFANA_URL}

techdocs:
  builder: 'local'
  publisher:
    type: 'local'
  generator:
    runIn: local


integrations:
  github:
    - host: github.com
      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
      # about setting up the GitHub integration here: https://backstage.io/docs/integrations/github/locations#configuration
      token: ${GITHUB_TOKEN}
