apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: EIC-DevOps
  description: "Einfochips DevOps Group"
spec:
  owner: devops
  domain: DevOps
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: project-a
  description: "PROJECT_A Group"
spec:
  owner: development
  domain: DevOps
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: project-b
  description: "PROJECT_B Group"
spec:
  owner: development
  domain: DevOps